In [458]:
import numpy as np

In [459]:
positions = np.random.random(10).reshape(5,2)*2
speeds = np.random.random(10).reshape(5,2)*0.1
print(positions)
print(speeds)

[[1.98977872 0.13706154]
 [0.14722622 1.23499066]
 [0.17182956 0.36158629]
 [0.64157897 0.79555384]
 [1.8437969  1.07807606]]
[[0.05397784 0.09111457]
 [0.03784174 0.07162615]
 [0.06092985 0.05740398]
 [0.07900904 0.00426106]
 [0.04185402 0.04590815]]


In [460]:
outside = np.ma.masked_outside(positions, (0.2,0.2),(1.5,1.5))
print(f'Outside {outside}')
print(f'Outside values of position \n{positions[outside.mask]}')

Outside [[-- --]
 [-- 1.2349906601649987]
 [-- 0.3615862948486772]
 [0.6415789730036885 0.7955538378559328]
 [-- 1.0780760596518602]]
Outside values of position 
[1.98977872 0.13706154 0.14722622 0.17182956 1.8437969 ]


Count outside values

In [461]:
count_to_replace = np.count_nonzero(outside.mask == True)

Generation of random values for required data given `count_to_replace`

In [462]:
r_values = np.random.random(count_to_replace)

Fill only missing values

In [463]:
r_values

array([0.22440808, 0.38679914, 0.37268586, 0.68398974, 0.88727745])

In [464]:
positions[outside.mask] = r_values

In [465]:
positions


array([[0.22440808, 0.38679914],
       [0.37268586, 1.23499066],
       [0.68398974, 0.36158629],
       [0.64157897, 0.79555384],
       [0.88727745, 1.07807606]])

In [466]:
print(f'POS {positions}')
mask = positions[0:] > 1.
print(f'MASK {mask}')
print(f'positions[mask] {positions[mask]}')
positions[mask] = 1.
print(f'positions[mask] {positions[mask]}')
print(f'position {positions}')

POS [[0.22440808 0.38679914]
 [0.37268586 1.23499066]
 [0.68398974 0.36158629]
 [0.64157897 0.79555384]
 [0.88727745 1.07807606]]
MASK [[False False]
 [False  True]
 [False False]
 [False False]
 [False  True]]
positions[mask] [1.23499066 1.07807606]
positions[mask] [1. 1.]
position [[0.22440808 0.38679914]
 [0.37268586 1.        ]
 [0.68398974 0.36158629]
 [0.64157897 0.79555384]
 [0.88727745 1.        ]]
