# Assignments of outside particles

Particles are enclosed in a window box whose _length_ and _high_ are:

- `window.size.x`
- `window.size.y`

When they reach the border, they're assigned to a new random position around the center.

In [256]:
import numpy as np

delta = 10


positions = np.zeros((50,2)).astype(float)
positions[:] = np.vstack( ( np.random.randint(-10,110,50), np.random.randint(-10,110,50)) ).T
speeds = np.random.random(10).reshape(5,2)*0.1
print(f'Positions \n{positions}')
print(f'Speed \n{speeds}')

Positions 
[[  2.  -3.]
 [ 38.  94.]
 [ 20.  91.]
 [ 56.  65.]
 [ 32.  27.]
 [ 89.  42.]
 [ 42. -10.]
 [ 23.   4.]
 [ 88. 101.]
 [ 78.  91.]
 [ 24.   2.]
 [ 95.  61.]
 [ -5.  -8.]
 [ 84.  -3.]
 [ 13.  80.]
 [ 68.   3.]
 [ 46.  10.]
 [ 39.  -5.]
 [  8.  72.]
 [ 40.  75.]
 [  2.  53.]
 [ 30.  -7.]
 [ 17.  34.]
 [ 87.  92.]
 [ 54. 103.]
 [ 50.  38.]
 [ 67.  64.]
 [ 70.  80.]
 [  8.  49.]
 [ -5.  84.]
 [ 72.  45.]
 [ 16.   0.]
 [-10.  67.]
 [  2.  44.]
 [ 91.  -9.]
 [ 85.  61.]
 [ 79.  38.]
 [ 88.  69.]
 [ 88.  72.]
 [ 85.  28.]
 [ 34.  95.]
 [ 79.  57.]
 [103. 106.]
 [  3.  36.]
 [ 37.  13.]
 [  7.  33.]
 [ 73.   9.]
 [ 30.  50.]
 [ 41.  80.]
 [ 27.  78.]]
Speed 
[[0.01594197 0.05910873]
 [0.05921845 0.01846439]
 [0.05686757 0.04606374]
 [0.04334251 0.03510035]
 [0.07235195 0.08677306]]


## Filtering particles outside

Filtering is done with _masking_

We use `np.ma.masked_outside` with origin and most valued positions, so
`(0, 0)` and `(length, high)`

In [257]:
length=100
high=100

outside = np.ma.masked_outside(positions, (0.1,0.1),(length,high))
print(f'Outside {outside}')
print(f'Outside values of position \n{positions[outside.mask]}')

Outside [[2.0 --]
 [38.0 94.0]
 [20.0 91.0]
 [56.0 65.0]
 [32.0 27.0]
 [89.0 42.0]
 [42.0 --]
 [23.0 4.0]
 [88.0 --]
 [78.0 91.0]
 [24.0 2.0]
 [95.0 61.0]
 [-- --]
 [84.0 --]
 [13.0 80.0]
 [68.0 3.0]
 [46.0 10.0]
 [39.0 --]
 [8.0 72.0]
 [40.0 75.0]
 [2.0 53.0]
 [30.0 --]
 [17.0 34.0]
 [87.0 92.0]
 [54.0 --]
 [50.0 38.0]
 [67.0 64.0]
 [70.0 80.0]
 [8.0 49.0]
 [-- 84.0]
 [72.0 45.0]
 [16.0 --]
 [-- 67.0]
 [2.0 44.0]
 [91.0 --]
 [85.0 61.0]
 [79.0 38.0]
 [88.0 69.0]
 [88.0 72.0]
 [85.0 28.0]
 [34.0 95.0]
 [79.0 57.0]
 [-- --]
 [3.0 36.0]
 [37.0 13.0]
 [7.0 33.0]
 [73.0 9.0]
 [30.0 50.0]
 [41.0 80.0]
 [27.0 78.0]]
Outside values of position 
[ -3. -10. 101.  -5.  -8.  -3.  -5.  -7. 103.  -5.   0. -10.  -9. 103.
 106.]


No we count how random values we have to provide


In [258]:
count_to_replace = np.count_nonzero(outside.mask == True)

Generation of random values for required data given `count_to_replace`

In [259]:
r_values = np.random.random(count_to_replace)

Fill only missing values

In [260]:
r_values

array([0.2932754 , 0.11399026, 0.7815017 , 0.02478912, 0.82736806,
       0.89871294, 0.63102239, 0.79082082, 0.55961254, 0.50076136,
       0.63139505, 0.24239692, 0.67769614, 0.32713673, 0.32463013])

In [261]:
#positions[outside.mask] = r_values


HAlf

In [262]:
outside_x = np.ma.masked_outside(positions[:,0], 0, length)
print(f'Outside {outside_x}')
print(f'Outside data {outside_x.data}')
print(f'Positions {positions}')
print(f'Outside values of positions \n{positions[outside_x.mask]}')
count_x = np.count_nonzero(outside_x.mask == True)
print(f'f Count_x {count_x}')
r_values_x = np.random.randint(0, 10, count_x)
r_values_x += length// 2
print(f'r_values_x {r_values_x}')
positions[outside_x.mask,0] = r_values_x
print(f'Positions {positions}')

Outside [2.0 38.0 20.0 56.0 32.0 89.0 42.0 23.0 88.0 78.0 24.0 95.0 -- 84.0 13.0
 68.0 46.0 39.0 8.0 40.0 2.0 30.0 17.0 87.0 54.0 50.0 67.0 70.0 8.0 --
 72.0 16.0 -- 2.0 91.0 85.0 79.0 88.0 88.0 85.0 34.0 79.0 -- 3.0 37.0 7.0
 73.0 30.0 41.0 27.0]
Outside data [  2.  38.  20.  56.  32.  89.  42.  23.  88.  78.  24.  95.  -5.  84.
  13.  68.  46.  39.   8.  40.   2.  30.  17.  87.  54.  50.  67.  70.
   8.  -5.  72.  16. -10.   2.  91.  85.  79.  88.  88.  85.  34.  79.
 103.   3.  37.   7.  73.  30.  41.  27.]
Positions [[  2.  -3.]
 [ 38.  94.]
 [ 20.  91.]
 [ 56.  65.]
 [ 32.  27.]
 [ 89.  42.]
 [ 42. -10.]
 [ 23.   4.]
 [ 88. 101.]
 [ 78.  91.]
 [ 24.   2.]
 [ 95.  61.]
 [ -5.  -8.]
 [ 84.  -3.]
 [ 13.  80.]
 [ 68.   3.]
 [ 46.  10.]
 [ 39.  -5.]
 [  8.  72.]
 [ 40.  75.]
 [  2.  53.]
 [ 30.  -7.]
 [ 17.  34.]
 [ 87.  92.]
 [ 54. 103.]
 [ 50.  38.]
 [ 67.  64.]
 [ 70.  80.]
 [  8.  49.]
 [ -5.  84.]
 [ 72.  45.]
 [ 16.   0.]
 [-10.  67.]
 [  2.  44.]
 [ 91.  -9.]
 [ 85.  61.]
 [ 79.

In [263]:
def center_position_axe(pos_axe, radius, length):
    mask = np.ma.masked_outside(pos_axe, 0, length)
    size = np.count_nonzero(mask.mask==True)
    if size:
        values = np.random.randint(-radius + length, +radius +length, size)
        print(size, pos_axe, values)
        pos_axe[mask.mask] = values

In [264]:
foo = np.random.randint(-10,+60,100).reshape(50,2)
print(foo)
center_position_axe(foo[:,0], 10, 200)
center_position_axe(foo[:,1],10,600)
print(foo)



[[ -2  45]
 [ 16  13]
 [ 30  -3]
 [ 37  21]
 [ 47  -8]
 [ -3  55]
 [ -8  57]
 [ 38  -2]
 [ 33  28]
 [ 32  10]
 [ -2  36]
 [ 49  22]
 [ 57  -4]
 [ -4  13]
 [ -5  28]
 [ -6  38]
 [ -4  56]
 [ 14   6]
 [ 54  35]
 [ 25  27]
 [  9  17]
 [ 37   1]
 [  3  -8]
 [ 28  28]
 [ 34   7]
 [ 44  18]
 [ 51 -10]
 [ -4   1]
 [  6   3]
 [ 24  25]
 [ 11  -8]
 [ 52  37]
 [ 23  53]
 [ 53  18]
 [  3  26]
 [ 47   7]
 [ 26  49]
 [ -3  24]
 [ 44  39]
 [ 21  23]
 [  0   5]
 [ 47  42]
 [ 17  53]
 [ 10  35]
 [  2  15]
 [  6  59]
 [ 10  39]
 [ 22  40]
 [ 25  -2]
 [ 13  24]]
10 [-2 16 30 37 47 -3 -8 38 33 32 -2 49 57 -4 -5 -6 -4 14 54 25  9 37  3 28
 34 44 51 -4  6 24 11 52 23 53  3 47 26 -3 44 21  0 47 17 10  2  6 10 22
 25 13] [194 190 193 195 209 194 208 197 203 199]
8 [ 45  13  -3  21  -8  55  57  -2  28  10  36  22  -4  13  28  38  56   6
  35  27  17   1  -8  28   7  18 -10   1   3  25  -8  37  53  18  26   7
  49  24  39  23   5  42  53  35  15  59  39  40  -2  24] [598 596 595 602 601 608 591 609]
[[194  45]